---
apiVersion: gcp.platformref.dc24.io/v1alpha1
kind: Cluster
metadata:
  name: sandbox-dc6
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      provider: GCP
  location: europe-west3
  environment: sandbox-dc6
  project:
    id: f9db
    services:
      - compute.googleapis.com
      - dns.googleapis.com
      - file.googleapis.com
      - servicenetworking.googleapis.com
      - cloudkms.googleapis.com
      - certificatemanager.googleapis.com
      - secretmanager.googleapis.com
      - iap.googleapis.com
      - redis.googleapis.com
  kubernetes:
    nodes:
      count: 3
      size: small
