---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system