apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-system
spec:
  releaseName: crossplane
  interval: 5m
  chart:
    spec:
      chart: crossplane
      version: '1.14.3'
      sourceRef:
        kind: HelmRepository
        name: crossplane-repository
        namespace: crossplane-system
      interval: 1m
  values: 
    args:
      - '"--enable-environment-configs"'