---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-core
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./tools/crossplane/crossplane-core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system