name: Create a cluster
on:
  workflow_dispatch:
    inputs:
      cluster_name:
        required: true
        description: "The name of the cluster"
      location:
        required: true
        description: "The location of the cluster"
        default: "europe-west3"
      node_size:
        required: true
        description: "The size of the nodes"
        default: "small"
      node_count:
        required: true
        description: "The count of nodes in the new cluster"
        default: "1"

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup yq
        uses: frenck/action-setup-yq@v1
      - name: Create Cluster
        run: |
          ./scripts/add-cluster.sh ${{ inputs.cluster_name }} ${{ inputs.location }} ${{ inputs.node_size }} ${{ inputs.node_count }}
      - name: Commit Changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Create cluster ${{ inputs.name }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
